core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls'), name='webapp_urls'),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/models.py
from django.db import models
from django.shortcuts import reverse
import itertools
from django.utils.text import slugify


# Create your models here.

TECH = ((0, 'Inner Sphere'), (1, 'Clan'), (2, 'Prototype'))
ROLE = ((0, 'Ambusher'), (1, 'Brawler'), (2, 'Juggernaut'), (3, 'Missle Boat'), (4, 'Scout'), (5, "Skirmisher"), (6, 'Sniper'), (7, 'Striker'))
CLASSIFICATION = ((0, 'Light'), (1, 'Medium'), (2, 'Heavy'), (3, 'Assault'))
WEIGHTS = ((0, '20 Ton'), (1, '25 Ton'), (2, '30 Ton'), (3, '35 Ton'), (4, '40 Ton'), (5, '45 Ton'), (6, '50 Ton'), (7, '55 Ton'), (8, '60 Ton'), (9, '65 Ton'), (10, '70 Ton'), (11, '75 Ton'), (12, '80 Ton'), (13, '85 Ton'), (14, '90 Ton'), (15, '95 Ton'), (16, '100 Ton'))
STATUS = ((0, "Not Available"), (1, "Available"))


# This setup makes it so every Mech MUST have a pilot - maybe look into changing this

class Pilot(models.Model):
    """
    A Pilot will have a 1 2 1 relationship with a mech in Active Mech
    # TODO add User relationship
    """
    callsign = models.CharField(max_length=50, unique=True)
    gunnery = models.IntegerField(blank=True, default=4)
    piloting = models.IntegerField(blank=True, default=5)
    experience = models.IntegerField(blank=True, default=1000)
    edge = models.IntegerField(blank=True, default=1)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def save(self, *args, **kwargs):
        value = self.callsign
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.callsign
    
class Mech(models.Model):
    """
    A Pilot will have a 1 2 1 relationship with a mech in Active Mech
    """
    name = models.CharField(max_length=50, unique=True)
    category = models.IntegerField(choices=CLASSIFICATION, default=0)
    weight = models.IntegerField(choices=WEIGHTS, default=0)
    tech_level = models.IntegerField(choices=TECH, default=0)
    role = models.IntegerField(choices=ROLE, default=0)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    record_sheet = models.CharField(max_length=50, default='custom')
    battle_value = models.IntegerField(default=9999)
    status = models.IntegerField(choices=STATUS, default=0)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    
class ActiveMech(models.Model):
    name = models.CharField(max_length=50, unique=True)
    pilot = models.OneToOneField(Pilot, on_delete=models.CASCADE,
        primary_key=True, related_name="active_mech")
    mech = models.ForeignKey(Mech, on_delete=models.CASCADE,
                                 related_name="active_pilot")
    status = models.IntegerField(choices=STATUS, default=0)
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

templates/active_mech_detail.html
{% extends 'base.html' %} {% block content %}


<div class="container">

    <div class="row">
        <div class="col-4 mt-3 left">
            <h2>Mech Data</h2>
            <p>Name: {{ active_mech.mech.name }}</p>
            <p>Category: {{ active_mech.mech.get_category_display }}</p>
            <p>Weight: {{ active_mech.mech.get_weight_display }}</p>
            <p>Tech Level: {{ active_mech.mech.get_tech_level_display }}</p>
            <p>Role: {{ active_mech.mech.get_role_display }}</p>
            <p>Slug: {{ active_mech.mech.slug }}</p>
            <p>Description: {{ active_mech.mech.description }}</p>
            <p>Record Sheet: {{ active_mech.mech.record_sheet }}</p>
            <p>BV: {{ active_mech.mech.battle_value }}</p>
            <p>Status: {{ active_mech.mech.get_status_display }}</p>
        </div>
        <div class="col-4 mt-3 left">
            <h2>Pilot Data</h2>
            <p>{{ active_mech.pilot.callsign }}</p>
            <p>Gunnery: {{ active_mech.pilot.gunnery }}</p>
            <p>Piloting: {{ active_mech.pilot.piloting }}</p>
            <p>Experience: {{ active_mech.pilot.experience }}</p>
            <p>Status: {{ active_mech.pilot.get_status_display }}</p>
            <p>BV Modifier: {{ bv_mod }}</p>
        </div>
        <div class="col-4 mt-3 left">

        </div>
    </div>


</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Battletech Inventory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<body class="d-flex flex-column h-100 main-bg">
    {% load static %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Battletech Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'active_pilots' %}">Active Pilot</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'mechs' %}">Mech Inventory</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pilots' %}">Pilot Roster</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="#">Login</a>
                <a class="dropdown-item" href="#">Logout</a>
                </div>
            </li>
            </ul>
        </div>
    </nav>
    <div class="container message-container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- <main class="flex-shrink-0 main-bg"> -->
    <main class="d-flex align-items-center">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Bovine Hero</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2000);
    </script>   
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>This is Active Mechs List</h1>
    <div class="row">
      <ul>
        <li><span class="icon-mixed"></span>: Protype / Mixed Tech</li>
        <li><span class="icon-clan"></span>: Clan Tech</li>
        <li><span class="icon-inner-sphere"></span>: Successor State Tech</li>
      </ul>
        <!-- TODO Work on this -->
        <div class="col-12">
            <div class="row">
                <table class="table table-responsive-sm">
                  <thead>
                    <tr>
                      <!-- <th scope="col">#</th> -->
                      <th scope="col">Name</th>
                      <th scope="col">Pilot <a href="{% url 'pilot_create' %}"><i class="fa fa-plus-circle"></i></a></th>
                      <th scope="col">Mech <a href="{% url 'mech_create' %}"><i class="fa fa-plus-circle"></i></a></th>
                      <th scope="col">Tech Level</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for activemech in activemech_list %}
                    <tr>
                      <!-- <th scope="row">{{ activemech.pk }}</th> -->
                      <td>
                        <a href="{% url 'active_mech_detail' activemech.slug  %}">{{ activemech.name }}</a>
                      </td>
                      <td>
                        <a href="{% url 'pilot_detail' activemech.pilot.slug  %}">{{ activemech.pilot.callsign }}</a>
                        {{ activemech.pilot.gunnery }} /
                        {{ activemech.pilot.piloting }}
                      </td>
                      <td>
                        <a href="{% url 'mech_detail' activemech.mech.slug  %}">{{ activemech.mech}}</a> 
                      </td>
                      <td>
                        {% if activemech.mech.get_tech_level_display == "Inner Sphere" %}
                          <span class="icon-inner-sphere"></span>
                        {% elif activemech.mech.get_tech_level_display == "Clan" %}
                          <span class="icon-clan"></span>
                        {% else %}
                          <span class="icon-mixed"></span>
                        {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  </table>              
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
       pagination logic here
    </nav>
    {% endif %}

</div>
{%endblock%}

templates/mech_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
      <form method="post" class="card">
        {% csrf_token %}
        <h2>Delete Mech</h2>
        <p>Are you sure that you want to delete "{{ mech }}"?</p>
        <p class="form-buttons">
          <input type="submit" class="btn btn-primary" value="Delete">
          <a href="{% url 'mechs'%}" class="btn btn-outline">Cancel</a>
        </p>
      </form>
    </div>
</div>
{%endblock%}

templates/mech_detail.html
{% extends 'base.html' %} {% block content %}

{% load static %}
{% static "/" as baseUrl %}

<div class="container">

    <div class="row">
        <div class="col-12 left">
            <div class="image-container text-center">
                <img src="{{ baseUrl }}/images/mechs/{{ mech.slug }}-rg.png" alt="{{ mech.name }} Profile Picture" class="img-fluid img-thumbnail">
            </div>
        </div>
        <div class="col-12 left">
            <h2>Mech Data</h2>
            <p>Name: {{ mech.name }}</p>
            <p>
            {% if mech.get_tech_level_display == "Inner Sphere" %}
                <span class="icon-inner-sphere"></span>
            {% elif mech.get_tech_level_display == "Clan" %}
                <span class="icon-clan"></span>
            {% else %}
                <span class="icon-mixed"></span>
            {% endif %}
            </p>
            <p>Category: {{ mech.get_category_display }}</p>
            <p>Weight: {{ mech.get_weight_display }}</p>
            <p>Tech Level: {{ mech.get_tech_level_display }}</p>
            <p>Role: {{ mech.get_role_display }}</p>
            <p>Slug: {{ mech.slug }}</p>
            <p>Description: {{ mech.description }}</p>
            <p>Record Sheet: {{ mech.record_sheet }}</p>
            <p><a href="{{ baseUrl }}/readouts/{{ mech.record_sheet }}.pdf" download>Record Sheet</a></p>
            <p>BV: {{ mech.battle_value }}</p>
            <p>Status: {{ mech.get_status_display }}</p>
        </div>
        <div class="col-12 left">
            <div class="iframe-container">
                <iframe class="responsive-iframe" src="{{ baseUrl }}/images/readouts/{{ mech.record_sheet }}.pdf#view=FitH"></iframe>
            </div>
        </div>
    </div>


</div>

{% endblock content %}

templates/mechs.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Battlemechs</h1>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <p class="lead"><a href="{% url 'mech_create' %}"> Add a New Mech <i class="fas fa-plus-square"></i></a></p>
      </div>
    </div>
    <div class="row">

        <!-- Mech Entries -->
        <div class="col-12">
            <div class="row">
                <table class="table table-sm text-center">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Actions</th>
                        <th scope="col">Available</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for mech in mech_list %}
                      <tr>
                        <td>
                          <a href="{% url 'mech_detail' mech.slug  %}">{{ mech.name }}</a>
                        </td>
                        <td>
                          <div class="dropdown show">                 
                            <button class="btn dropdown-toggle btn-block" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fa fa-cogs"></i> Menu</a>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{% url 'mech_detail' mech.slug %}">
                                {% if mech.get_tech_level_display == "Inner Sphere" %}
                                  <span class="icon-inner-sphere"></span>
                                {% elif mech.get_tech_level_display == "Clan" %}
                                  <span class="icon-clan"></span> 
                                {% else %}
                                  <span class="icon-mixed"></span>
                                {% endif %} View Mech
                              </a>
                              <a class="dropdown-item " href="{{ baseUrl }}/images/readouts/{{ mech.record_sheet }}.pdf" download><i class="fa fa-download"></i> Download</a>
                              <a class="dropdown-item" href="{% url 'mech_update' mech.slug %}"><i class="fa fa-edit"></i> Edit</a>
                              <a class="dropdown-item" href="{% url 'mech_delete' mech.slug %}"><i class="fa fa-trash"></i> Delete</a>
                            </div>
                          </div>
                        </td>
                        <td>
                          <a href="{% url 'mech_toggle' mech.slug %}">
                            {% if mech.get_status_display == "Available" %}
                              <i class="fa fa-toggle-on"></i>
                            {% else %}
                              <i class="fa fa-toggle-off"></i>
                            {% endif %}
                          </a>
                        </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>              
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
    </nav>
    {% endif %}
</div>

{%endblock%}

templates/mechs_form.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
      <h2>Mech Form</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
          <button type="submit" value="Save">Submit</button>
        </p>
      </form>
    </div>
</div>
{%endblock%}

templates/pilot_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
      <form method="post" class="card">
        {% csrf_token %}
        <h2>Delete Pilot</h2>
        <p>Are you sure that you want to delete "{{ pilot }}"?</p>
        <p class="form-buttons">
          <input type="submit" class="btn btn-primary" value="Delete">
          <a href="{% url 'pilots'%}" class="btn btn-outline">Cancel</a>
        </p>
      </form>
    </div>
</div>
{%endblock%}

templates/pilot_detail.html
{% extends 'base.html' %} {% block content %}


<div class="container">

    <div class="row">
        <div class="col-4 mt-3 left">
            <h2>Pilot Data</h2>
            <p>{{ pilot.callsign }}</p>
            <p>Gunnery: {{ pilot.gunnery }}</p>
            <p>Piloting: {{ pilot.piloting }}</p>
            <p>Experience: {{ pilot.experience }}</p>
            <p>Status: {{ pilot.get_status_display }}</p>
            <p>BV Modifier: {{ bv_mod }}</p>
        </div>
    </div>

</div>

{% endblock content %}

templates/pilots.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>This is Pilots List</h1>
    <div class="row">

        <!-- Pilot Entries -->
        <div class="col-12 mt-3 left">
            <div class="row">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">callsign</th>
                        <th scope="col">gunnery</th>
                        <th scope="col">piloting</th>
                        <th scope="col">experience</th>
                        <th scope="col">edge</th>
                        <th scope="col">slug</th>
                        <th scope="col">status</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for pilot in pilot_list %}
                      <tr>
                        <th scope="row">{{ pilot.pk }}</th>
                        <td><a href="{% url 'pilot_detail' pilot.slug  %}">{{ pilot.callsign }}</a> <a href="{%url 'pilot_update' pilot.slug %}"> Edit</a></td>
                        <td>{{ pilot.gunnery }}</td>
                        <td>{{ pilot.piloting }}</td>
                        <td>{{ pilot.experience }}</td>
                        <td>{{ pilot.edge }}</td>
                        <td>{{ pilot.slug }} <a href="{%url 'pilot_delete' pilot.slug %}"> Delete</a></td>
                        <td>{{ pilot.get_status_display }} </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>              
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
       pagination logic here
    </nav>
    {% endif %}
</div>
{%endblock%}